spring:
  application:
    name: ms-client
  datasource:
   url: jdbc:postgresql://db-banco:5432/banco_db
   username: postgres
   password: root
   driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # Crea las tablas autom√°ticamente
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
